### ISSUE TITLE
jetty-deps repository has moved?

### ISSUE THREAD

**Issue by projectgus** [kaikreuzer/openhab-core#12]
Hi,

I'm trying to bring up a new openhab development environment on my Debian machine, using the Eclipse installer method as per the openhab-distro [ide.md guide](https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/ide.md). I haven't had a lot of luck yet.

In openhab-core, running 'mvn clean install' in master branch commit 5d92d162f  fails for me with these lines:

```
[INFO] Adding repository https://github.com/openhab/openhab.repo/raw/master/jetty-deps
[ERROR] Failed to resolve target definition /home/gus/dev/openhab2/git/openhab-core/targetplatform/openhab.target: Failed to load p2 metadata repository from location https://github.com/openhab/openhab.repo/raw/master/jetty-deps: No repository found at https://github.com/openhab/openhab.repo/raw/master/jetty-deps. -> [Help 1]
```

The repository is referenced from https://github.com/kaikreuzer/openhab-core/blob/master/targetplatform/openhab.target#L115

The referenced repo seems to have existed recently but no longer exists now. If I comment that `<location>` out then I get errors for missing dependencies of jetty, which seems to follow from the name!

I've tried to find a new repo/URL that jetty-deps might have been moved to, but I'm not having any luck yet.

Apologies in advance if I'm just doing things totally wrong, I'm not very familiar with openhab's codebase yet!

**Comment by kaikreuzer** [comment]
This is indeed momentarily broken, but will be fixed today - see https://github.com/openhab/openhab2-addons/pull/637#issuecomment-173487364. Thanks for your patience :-)

**Comment by projectgus** [comment]
Thanks for the quick and helpful reply! I will sit tight and try again tomorrow.

**Comment by kaikreuzer** [comment]
should be fixed by https://github.com/kaikreuzer/openhab-core/pull/13

**Comment by projectgus** [comment]
Thanks for the quick update Kai, all good now!
