### ISSUE TITLE
Un-synced code changes

### ISSUE THREAD

**Issue by watou** [kaikreuzer/openhab-core#19]
@kaikreuzer, I noticed in compat1x code today that some of the changes in [this PR](https://github.com/openhab/openhab/pull/3016/files#diff-371235bb0243afa40128c0a2adc19b98L13) from a few months ago don't appear in the compat1x layer.  I don't know how much of the code should be represented here or in ESH.

**Comment by kaikreuzer** [comment]
Thanks for noticing, @watou! It seems that it was indeed overlooked in https://github.com/openhab/openhab/pull/3016 that it included changes of the core classes as well.
