### ISSUE TITLE
Add Missing Icons

### ISSUE THREAD

**Issue by reitermarkus** [kaikreuzer/openhab-core#21]
The following icons (according to the [smarthome channel categories](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channel-categories)) are still missing from the icon set, which will be moved to [eclipse/smarthome](https://github.com/eclipse/smarthome/tree/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic) upon completion.

- [x] Alarm `siren`
- [x] Battery `battery`
- [x] Blinds `rollershutter`
- [x] ColorLight `colorwheel`/`rgb`
- [x] Contact `contact`
- [x] DimmableLight `slider`
- [x] CarbonDioxide	`co2`
- [x] Door `door`/`frontdoor`
- [x] Energy `energy`/`solarplant`
- [x] Fan `fan_box`/`fan_ceiling`
- [x] Fire `fire`
- [x] Flow `flow`
- [x] GarageDoor `garagedoor`
- [x] Gas `gas`
- [x] Humidity `humidity `
- [x] Light	`light`
- [x] Motion `motion`
- [x] MoveControl `move`
- [x] Player `receiver`/`television`
- [x] PowerOutlet `socket`
- [x] Pressure `pressure`
- [x] QualityOfService `signal`
- [x] Rain `rain`/`cistern`
- [x] Recorder `microphone`
- [x] Smoke `smoke`
- [x] SoundVolume `volume`	
- [x] Switch `switch`
- [x] Temperature `temperature`
- [x] Water `water`/`cistern`
- [x] Wind	`wind`
- [x] Window `contact`
- [x] Zoom `zoom`

**Comment by reitermarkus** [comment]
@kaikreuzer, could you elaborate a bit on the following categories? I can't think of an icon that would fit them.

- MoveControl
- QualityOfService
- Recorder

**Comment by kaikreuzer** [comment]
I would suggest something like
- [this](https://d11yb1vz45mxf2.cloudfront.net/b04d85eb8f49e5d33301/images/move-icon.png) for MoveControl
- [this](https://lh3.googleusercontent.com/xHfUt4IJowAq5V6lc4B4VUact68GIsmFEVL39Pirkzkl7Z_TCRByHySmIue3Wp6tVBY=w300) for Recoder
- and refer to the [signal strength channel](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channels) for QualityOfService and use something like a [Wifi icon](https://cdn2.iconfinder.com/data/icons/flaticons-stroke/18/wifi-1-512.png), where you can also have the different options _0,..._4 for 5 states.

Would that do?

**Comment by reitermarkus** [comment]
Thanks, I thought about a cell tower for the QoS icon, or simply signal bars, before, but wasn't sure exactly what this would be used for. Thanks for pointing out the signal strength channel as an example.

**Comment by kaikreuzer** [comment]
Wow, you are quick!
Just one note regarding the PR: The icons for the categories must exactly match the name of the categories (and only be converted to lower case), e.g. we need a `movecontrol.svg` and a `qualityofservice_3.svg`, etc. Could you adapt that?

Btw, in future, we can also think about defining the aliases in some simple file, which could be processed by the [icon provider](https://github.com/kaikreuzer/openhab-core/blob/master/bundles/org.openhab.ui.iconset.classic/src/main/java/org/openhab/ui/iconset/classic/internal/ClassicIconProvider.java) - this would allow us supporting aliases without having to duplicate the physical resources.

**Comment by reitermarkus** [comment]
I only was quick because I had nothing else to do. =)

And you are right, duplicate files are less than ideal. As you can see in my shellscript, there should be some rules for icon names. I think these suffixes should be equivalent:

contact | switch | rollershutter
----------|---------| -------
closed  | on     |  100
open    | off      |  0

**Comment by kaikreuzer** [comment]
Yes, the current implementation already has some logic of checking what exists and serving the best available resource - see [here] for the applied logic. This is the code that I meant can be enhanced to support the aliases that we would want. But for the start, I think we can go with the duplicated resources and your shell script.

**Comment by reitermarkus** [comment]
Ok, I'll leave my current names intact for now and just add the new ones to the script. I think it's easier to search for `microphone` and `signal` than it is for `recorder` and `qualityofservice`.

Quick question: Does it have to be named `qualityofservice_3` or can it also be a normal dash?

**Comment by kaikreuzer** [comment]
(just fixed the "here" link above)

Sorry, that was my mistake - it actually HAS to be a normal dash, i.e. `qualityofservice-3`.

**Comment by reitermarkus** [comment]
Ok, all should have the right name now. I renamed the `slider` icons to `dimmablelight` in the process, should these still exist?

**Comment by kaikreuzer** [comment]
Yes, slider should still exist, because this is the default icon for any slider widget that does not have any other icon defined.

**Comment by reitermarkus** [comment]
Ok, readded the `slider` icons, should be good now.

**Comment by kaikreuzer** [comment]
Thanks a lot!
So the next step would be to move these icons to ESH. Could you create such a PR?
See [here](https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md#contributing-to-eclipse-smarthome) for the requirements for contributions (you need a CLA and sign-off your commits).

It would be cool if you could also come up with a script to directly fill the [sample section on the README.md](https://github.com/eclipse/smarthome/blob/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.md#samples) - we would then have the icons directly on our [official documentation](https://www.eclipse.org/smarthome/documentation/features/ui/iconset/classic/readme.html).

**Comment by reitermarkus** [comment]
https://github.com/eclipse/smarthome/pull/1067
