### ISSUE TITLE
compat1x NPE

### ISSUE THREAD

**Issue by watou** [kaikreuzer/openhab-core#24]
The [EventPublisherImpl in 1.x core](https://github.com/openhab/openhab/blob/1.8/bundles/core/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventPublisherImpl.java#L77) generates a logger.warn message when a null State is passed.

The [EventPublisherDelegate in compat1x](https://github.com/kaikreuzer/openhab-core/blob/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/events/EventPublisherDelegate.java#L60) attempts to reference the possibly null newState while trying to log a warning message.

Observed [here](https://community.openhab.org/t/mqtt-switch-help/5158/7?u=watou).

**Comment by maggu2810** [comment]
and AFAIK we should not call toString for logging arguments. The toString method eill be called also if the logging is not done (e.g. log level settings).
http://www.slf4j.org/faq.html#string_contents

**Comment by kaikreuzer** [comment]
@watou Thanks for the analysis!
@maggu2810 Good remark - I have removed the toString calls.
