### ISSUE TITLE
NRJavaserial is out of date

### ISSUE THREAD

**Issue by jspuij** [kaikreuzer/openhab-core#29]
Hi @kaikreuzer ,

I've noticed that the nrjavaserial library has not been updated in openhab for more than a year. Is there any reason not to upgrade to the latest version of the library? There are quite a few fixes in there for embedded systems and native support for FreeBSD. Both very welcome I guess.

If you want me to pick this up and create a pull request, NP.

**Comment by kaikreuzer** [comment]
See https://github.com/NeuronRobotics/nrjavaserial/issues/29 and https://github.com/NeuronRobotics/nrjavaserial/issues/44 on why I am still on 3.9.3.
I would want to upgrade to 3.12, hoping that above issues are solved there and that it also includes https://github.com/NeuronRobotics/nrjavaserial/issues/72.
Feel free to help on the nrjavaserial project to get that new release out of the door!

**Comment by jspuij** [comment]
Thanks for the info. I suspected as much. Will have a look at those nrjavaserial issues. Thanks!

**Comment by watou** [comment]
Tying this subject to a new binding that includes its own 3.11.0 nrjavaserial due to bugs in 3.9.3 on Windows.

https://github.com/openhab/openhab/pull/3883#issuecomment-215919169

**Comment by kaikreuzer** [comment]
There wasn't any activity on nrjavaserial project since May this year - it appears to be almost abandoned... Anybody interested to fork it and revive it?
