### ISSUE TITLE
Generated certificate with small key length

### ISSUE THREAD

**Issue by lolodomo** [kaikreuzer/openhab-core#48]
The generated certificate used when connecting to openHAB through HTTPS has a public key with a size of 256.
Isn't it a small lenght ?
As a comparison, openHAB 1.8 certificate uses a public key with a size of 2048.

**Comment by kaikreuzer** [comment]
@Stratehm, could you comment on this?

**Comment by Stratehm** [comment]
The certificate uses keys generated with [Elliptic Curves Cryptography](https://en.wikipedia.org/wiki/Elliptic_curve_cryptography). The 256 bits Elliptic Curves keys have the same cryptography strengh as RSA 3072 bits keys (OpenHAB 1.x uses 2048 bits RSA keys).

**Comment by lolodomo** [comment]
Ok thank you for the explanation.
