### ISSUE TITLE
restdocs not working when not using it on localhost

### ISSUE THREAD

**Issue by kaikreuzer** [kaikreuzer/openhab-core#7]
I just tried the latest distro and noticed that the restdocs are not working if being used from a remote machine (i.e. not on localhost).

<img width="979" alt="bildschirmfoto 2016-01-06 um 19 21 25" src="https://cloud.githubusercontent.com/assets/3244965/12150555/ba2e6368-b4aa-11e5-8045-b4a6643b3580.png">

@dvanherbergen Did I somehow miss some fix from you? I thought that this was solved already...

**Comment by dvanherbergen** [comment]
Strange, I'll have a look.

**Comment by dvanherbergen** [comment]
OK, so the initial load of the page works correctly. It also correctly requests page content from the correct host. But then the swagger servlet responds with content containing the wrong host.

It looks like the swagger servlet is embedding the URL configured [here] (https://github.com/openhab/openhab-distro/blob/master/distributions/distribution-resources/src/main/resources/runtime/etc/services.cfg#L28) in the response.

**Comment by dvanherbergen** [comment]
And the solution is simple. We just need to delete that line. I will create a PR.

**Comment by kaikreuzer** [comment]
Thanks!
